# Generated by Django 2.2.3 on 2019-08-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_auto_20190816_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Messanger', to='massage.Massanger'),
        ),
    ]
