# Generated by Django 2.2.3 on 2019-08-16 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_auto_20190816_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Messanger', to=settings.AUTH_USER_MODEL),
        ),
    ]
